export const API_ENDPOINTS = {
  loadVendor: `/purchase/loadVendor`,
  loadInvoice: `/purchase/loadInvoice`,
  getUnitPrice: `/purchase/getUnitPrice`,    
  getPurchase: `/purchase/get`,
  save: `/purchase/save`,
  updatePurchase: `/purchase/update`,
  saveReturn: `/purchase/saveReturn`, 
  loadfilterData: `/purchase/loadfilterData`, 
  loadVendorItem: `/purchase/loadVendorItem`, 
  getVendorDetails: `/purchase/getVendorDetails`,     
  remove: `/purchase/remove`,
  removePartId: `/purchase/removePartId`,  
  loadCategory: `/category/load`,
  loadCategoryName: `/category/loadCategoryName`,  
  loadItemName: `/item/loadItemName`,
  load: `/item/load`,
  GET_PURCHASE_ORDER_LIST: `/purchase/loadPO`,
  ADD_PURCHASE_ORDER_LIST: `/purchase/savePO`,
  REMOVE_PURCHASE_ORDER: `/purchase/removePO`,
  UPDATE_PURCHASE_ORDER: `/purchase/updatePurchaseOrder`,
  CREATE_INVOICE:`/purchase/createInvoice`,
  CREATE_RETURN:`/purchase/createReturn`,
  lOADRETURN:`/purchase/loadReturn`,

  CREATE_STOCK:`/stock/createStock`,
};
